tap "1password/tap"
tap "anomalyco/tap"
tap "azure/azure-workload-identity", "https://github.com/Azure/homebrew-azure-workload-identity"
tap "controlplaneio-fluxcd/tap"
tap "derailed/popeye"
tap "dotenv-org/brew"
tap "fluxcd/tap"
tap "homebrew/services"
tap "legit-labs/legit-labs"
tap "loft-sh/tap"
tap "one2nc/cloudlens"
tap "theurichde/go-aws-sso"
# GitOps Continuous Delivery for Kubernetes
brew "argocd"
# Record and share terminal sessions
brew "asciinema"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Official Amazon AWS command-line interface
brew "awscli"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Install RubyGems as Homebrew formulae
brew "brew-gem"
# Prevent cloud misconfigurations during build-time for IaC tools
brew "checkov"
# Home for bootstrapping, AMI, EKS, and other helpers in Cluster API Provider AWS
brew "clusterawsadm"
# Home for the Cluster Management API work, a subproject of sig-cluster-lifecycle
brew "clusterctl"
# GNU File, Shell, and Text utilities
brew "coreutils"
# CLI and validation tools for Kubelet Container Runtime Interface (CRI)
brew "cri-tools"
# Enterprise friendly way of detecting and preventing secrets in code
brew "detect-secrets"
# Load/unload environment variables based on $PWD
brew "direnv"
# Simple command-line tool for creating clusters on Amazon EKS
brew "eksctl"
# GitHub command-line tool
brew "gh"
# Audit git repos for secrets
brew "gitleaks"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Fast linters runner for Go
brew "golangci-lint"
# Kubernetes package manager
brew "helm"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c@76"
# Cost estimates for Terraform, Terragrunt, and CloudFormation
brew "infracost"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Run local Kubernetes cluster in Docker
brew "kind"
# Fast and secure open-source backup
brew "kopia"
# CLI tool to discover unused Kubernetes resources
brew "kor"
# Colorize your kubectl output
brew "kubecolor"
# FAST Kubernetes manifests validator, with support for Custom Resources!
brew "kubeconform"
# Collection of commands to fill in the gaps between Terraform, Helm, and Kubectl
brew "kubergrunt"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Much more powerful alternative to kubectx and kubens
brew "kubie"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# Postgres C API library
brew "libpq", link: true
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Drop-in replacement for Terraform. Infrastructure as Code Tool
brew "opentofu"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Python package management tool
brew "poetry"
# Command-line shell and scripting language
brew "powershell", link: false
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Password generator
brew "pwgen"
# Python version management
brew "pyenv"
# Persistent key-value database, with built-in net interface
brew "redis"
# Automated dependency updates. Flexible so you don't need to be
brew "renovate"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Editor of encrypted files
brew "sops"
# Cross-shell prompt for astronauts
brew "starship"
# Tool to generate documentation from Terraform modules
brew "terraform-docs"
# Thin wrapper for Terraform e.g. for locking state
brew "terragrunt"
# Linter for Terraform files
brew "tflint"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Disaster recovery for Kubernetes resources and persistent volumes
brew "velero"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# A utility CLI that helps manage Azure AD Workload Identity and automate error-prone operations:
brew "azure/azure-workload-identity/azwi", trusted: true
# Flux Operator CLI
brew "controlplaneio-fluxcd/tap/flux-operator", trusted: true
# A Kubernetes Cluster sanitizer and linter!
brew "derailed/popeye/popeye", trusted: true
# Flux CLI
brew "fluxcd/tap/flux", trusted: true
# Command-line interface for 1Password
cask "1password-cli"
cask "adoptopenjdk"
# Interactive CLI tool for AWS Single Sign-On (SSO)
cask "theurichde/go-aws-sso/go-aws-sso", trusted: true
cask "powershell"
vscode "4ops.terraform"
vscode "adamhartford.vscode-base64"
vscode "arjun.swagger-viewer"
vscode "aykutsarac.jsoncrack-vscode"
vscode "byi8220.indented-block-highlighting"
vscode "davidanson.vscode-markdownlint"
vscode "docker.docker"
vscode "donjayamanne.githistory"
vscode "formulahendry.code-runner"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "hilleer.yaml-plus-json"
vscode "iciclesoft.workspacesort"
vscode "iliazeus.vscode-ansi"
vscode "jtr.vscode-position"
vscode "mermaidchart.vscode-mermaid-chart"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.makefile-tools"
vscode "redhat.vscode-yaml"
vscode "ryanolsonx.solarized"
vscode "solomonkinard.git-blame"
vscode "streetsidesoftware.code-spell-checker"
vscode "vstirbu.vscode-mermaid-preview"
vscode "yzhang.markdown-all-in-one"
vscode "zainchen.json"
go "github.com/aws/aws-lambda-go/cmd/build-lambda-zip"
go "golang.org/x/tools/cmd/goimports"
go "golang.org/x/tools/gopls"
go "github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb"
go "honnef.co/go/tools/cmd/staticcheck"
go "github.com/swaggo/swag/cmd/swag"
